server:
  port: 9000

rsa:
  private-key: "file:../../.spring_config/certs/private.pem"
  public-key: "file:../../.spring_config/certs/public.pem"


spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: com.jaddy.calendarresourceoauth.utils.PostgreSQL94CustomDialect
  datasource:
    driver-class-name: ${prod-env-driver}
    url: ${prod-env-url}
    username: ${prod-env-user}
    password: ${prod-env-psswrd}
  application:
    name: calendar-resource-oauth

logging:
  level:
    org.springframework.security: TRACE
    web: TRACE
    root: INFO
    org.springframework.data.jpa: trace

