server:
  port: 9000

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"



spring:
  datasource:
    url: jdbc:postgresql://authdb-example.crfc6n1khr2t.us-east-1.rds.amazonaws.com/authexampledb
    username: jadams
    driver-class-name: org.postgresql.Driver
    password: Adam1212DB

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: com.jaddy.calendarresourceoauth.utils.PostgreSQL94CustomDialect


#    generate-ddl: true

#JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'

logging:
  level:
    org.springframework.security: TRACE
    web: TRACE
    root: INFO
    org.springframework.data.jpa: trace

