FROM openjdk:17-alpine
MAINTAINER jadams
VOLUME docker_lavishAPIServer_1
COPY CalendarResourceOAuth-0.0.1-SNAPSHOT.jar CalendarResource-1.0.0.jar
ENTRYPOINT ["java","-jar","/CalendarResource-1.0.0.jar"]